version: "3.9"

services:
  counter-service:
    build:
      context: .
      dockerfile: DivisorCounter/Dockerfile
    depends_on:
      - cache-service
    restart: on-failure
    image: saidmansour/divisorcounter-counterservice:$BUILD_NUMBER
  cache-service:
    build:
      context: .
      dockerfile: CacheService/Dockerfile
    depends_on:
      - cache-db
    ports:
      - "5007:80"
    deploy:
      replicas: 1
    restart: on-failure
    image: saidmansour/divisorcounter-cacheservice:$BUILD_NUMBER

  cache-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "cache-database"
      MYSQL_USER: "div-cache"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
